### ISSUE TITLE
Loaded: loaded (/usr/lib/systemd/system/ssmanager.service; disabled; vendor preset: disabled)

### ISSUE THREAD

**Issue by DongDeming** [Andesome/shadowsocks-libev-sh#1]
执行脚本的过程中ssmanager.service; config.json 内容为空，需要手动拷贝之后才能执行systemctl start ssmanager.service

**Comment by lllyin** [comment]
[commit](https://github.com/Andesome/shadowsocks-libev-sh/commit/95dd4feb5aa95280761c91ab804716237ba814ca)已修复。
